authentication_token:
  path: /token
  methods: ['POST']

register:
  path: /register
  controller: App\Controller\AuthController::register
  methods: POST

api:
  path: /api
  controller: App\Controller\AuthController::api

authentication_validate:
  path: /authentication_validate
  controller: App\Controller\AuthController::validateToken
  methods: POST
